name: Testes Automatizados Postman

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Baixando os arquivos do repositório
        uses: actions/checkout@v4

      - name: Instalando o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalando o Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Rodando os testes da Petstore
        run: |
          newman run api-tests/petstore-collection.json \
            --environment api-tests/petstore-environment.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export api-tests/report.html

      - name: Salvando o relatório
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: api-tests/report.html
